import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { DoctorSchedule } from './schedule.entity';
import { DoctorSettings } from '../settings/entities/doctor-settings.entity';

/**
 * Service to automatically initialize doctor schedules from their settings
 * when patients attempt to book appointments.
 */
@Injectable()
export class AutoScheduleInitializerService {
    constructor(
        @InjectRepository(DoctorSchedule)
        private readonly scheduleRepo: Repository<DoctorSchedule>,
        @InjectRepository(DoctorSettings)
        private readonly settingsRepo: Repository<DoctorSettings>,
    ) { }

    /**
     * Auto-initialize a schedule for a doctor on a specific date if:
     * 1. No schedule exists yet
     * 2. Doctor has settings configured
     * 3. The date falls on a working day
     * 
     * @param doctorId - The doctor's ID
     * @param date - The date to check/initialize (Date object or string)
     * @returns true if initialized, false if already exists or can't initialize
     */
    async autoInitializeScheduleIfNeeded(
        doctorId: string,
        date: string | Date,
    ): Promise<boolean> {
        // Normalize date to midnight
        const dateObj = this.normalizeToDate(date);

        // Check if schedule already exists
        const existingSchedule = await this.scheduleRepo.findOne({
            where: { doctorId, date: dateObj },
        });

        if (existingSchedule) {
            return false; // Already initialized
        }

        // Fetch doctor settings
        const settings = await this.settingsRepo.findOne({
            where: { doctorId },
        });

        if (!settings || !settings.availableDays || settings.availableDays.length === 0) {
            return false; // No settings configured
        }

        // Check if this date is on a working day
        const dayOfWeek = dateObj.getDay();
        const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
        const currentDayName = dayNames[dayOfWeek];

        const isWorkingDay = settings.availableDays.some(
            (day) => day.toLowerCase() === currentDayName.toLowerCase(),
        );

        if (!isWorkingDay) {
            return false; // Not a working day
        }

        // Don't auto-initialize past dates
        const today = this.normalizeToDate(new Date());
        if (dateObj < today) {
            return false;
        }

        // Create default schedule with Morning and Evening sessions enabled
        const newSchedule = this.scheduleRepo.create({
            doctorId,
            date: dateObj,
            sessions: {
                morning: true,
                break: false,
                evening: true,
            },
            slotDuration: settings.appointmentDuration || 30,
            slots: [], // Slots will be auto-generated by getDaySchedule
        });

        await this.scheduleRepo.save(newSchedule);
        return true;
    }

    private normalizeToDate(date: string | Date): Date {
        if (date instanceof Date) {
            return new Date(date.getFullYear(), date.getMonth(), date.getDate());
        }
        const d = new Date(date);
        return new Date(d.getFullYear(), d.getMonth(), d.getDate());
    }
}
